# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Human_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Human_Widget(object):
    def setupUi(self, Human_Widget):
        Human_Widget.setObjectName("Human_Widget")
        Human_Widget.resize(1000, 800)
        self.layoutWidget = QtWidgets.QWidget(Human_Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 100, 800, 600))
        self.layoutWidget.setObjectName("layoutWidget")
        self.setagebox = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.setagebox.setContentsMargins(0, 0, 0, 0)
        self.setagebox.setObjectName("setagebox")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.seetagelay = QtWidgets.QHBoxLayout()
        self.seetagelay.setObjectName("seetagelay")
        self.setagetext = QtWidgets.QLabel(self.groupBox)
        self.setagetext.setObjectName("setagetext")
        self.seetagelay.addWidget(self.setagetext)
        self.setageslider = QtWidgets.QSlider(self.groupBox)
        self.setageslider.setMaximum(100)
        self.setageslider.setOrientation(QtCore.Qt.Horizontal)
        self.setageslider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.setageslider.setObjectName("setageslider")
        self.seetagelay.addWidget(self.setageslider)
        self.verticalLayout_2.addLayout(self.seetagelay)
        self.ageintlay = QtWidgets.QHBoxLayout()
        self.ageintlay.setObjectName("ageintlay")
        self.agereslabel = QtWidgets.QLabel(self.groupBox)
        self.agereslabel.setObjectName("agereslabel")
        self.ageintlay.addWidget(self.agereslabel)
        self.agerestext = QtWidgets.QLineEdit(self.groupBox)
        self.agerestext.setObjectName("agerestext")
        self.ageintlay.addWidget(self.agerestext)
        self.verticalLayout_2.addLayout(self.ageintlay)
        self.agestrlay = QtWidgets.QHBoxLayout()
        self.agestrlay.setObjectName("agestrlay")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.agestrlay.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.agestrlay.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.agestrlay)
        self.setagebox.addWidget(self.groupBox)
        self.setnamebox = QtWidgets.QGroupBox(self.layoutWidget)
        self.setnamebox.setObjectName("setnamebox")
        self.layoutWidget1 = QtWidgets.QWidget(self.setnamebox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 421, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name = QtWidgets.QLabel(self.layoutWidget1)
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.namelabel = QtWidgets.QLabel(self.layoutWidget1)
        self.namelabel.setObjectName("namelabel")
        self.horizontalLayout_4.addWidget(self.namelabel)
        self.nametext = QtWidgets.QLineEdit(self.layoutWidget1)
        self.nametext.setObjectName("nametext")
        self.horizontalLayout_4.addWidget(self.nametext)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.close = QtWidgets.QPushButton(self.setnamebox)
        self.close.setGeometry(QtCore.QRect(70, 140, 281, 81))
        self.close.setStyleSheet("background-image: url(:/jpgs/images/time.jpg);\n"
"color: rgb(255, 0, 0);\n"
"font: 30pt \"楷体\";\n"
"color: rgb(255, 170, 127);")
        self.close.setCheckable(False)
        self.close.setAutoRepeat(False)
        self.close.setAutoExclusive(False)
        self.close.setAutoDefault(True)
        self.close.setDefault(True)
        self.close.setObjectName("close")
        self.close.raise_()
        self.layoutWidget.raise_()
        self.setagebox.addWidget(self.setnamebox)

        self.retranslateUi(Human_Widget)
        self.close.clicked.connect(Human_Widget.close)
        QtCore.QMetaObject.connectSlotsByName(Human_Widget)

    def retranslateUi(self, Human_Widget):
        _translate = QtCore.QCoreApplication.translate
        Human_Widget.setWindowTitle(_translate("Human_Widget", "Human_Widget"))
        self.groupBox.setTitle(_translate("Human_Widget", "年龄设置"))
        self.setagetext.setText(_translate("Human_Widget", "设置年龄"))
        self.agereslabel.setText(_translate("Human_Widget", "ageChange(int)响应"))
        self.label_3.setText(_translate("Human_Widget", "ageChange(str)响应"))
        self.setnamebox.setTitle(_translate("Human_Widget", "姓名设置"))
        self.name.setText(_translate("Human_Widget", "输入姓名"))
        self.lineEdit.setText(_translate("Human_Widget", "Mike"))
        self.checkBox.setText(_translate("Human_Widget", "设置姓名"))
        self.namelabel.setText(_translate("Human_Widget", "nameChange(str)响应"))
        self.close.setText(_translate("Human_Widget", "关闭"))

from GUI.Demo.Demo1 import resource_human_rc