# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelloWorld.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintHello(object):
    def setupUi(self, PrintHello):
        PrintHello.setObjectName("PrintHello")
        PrintHello.resize(800, 600)
        PrintHello.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(PrintHello)
        self.centralwidget.setObjectName("centralwidget")
        self.LabHello = QtWidgets.QLabel(self.centralwidget)
        self.LabHello.setEnabled(True)
        self.LabHello.setGeometry(QtCore.QRect(210, 70, 291, 161))
        self.LabHello.setFrameShape(QtWidgets.QFrame.Panel)
        self.LabHello.setLineWidth(2)
        self.LabHello.setTextFormat(QtCore.Qt.AutoText)
        self.LabHello.setScaledContents(False)
        self.LabHello.setObjectName("LabHello")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(420, 210, 80, 20))
        self.close.setAutoDefault(False)
        self.close.setDefault(True)
        self.close.setFlat(False)
        self.close.setObjectName("close")
        self.Start = QtWidgets.QLabel(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(220, 180, 141, 31))
        self.Start.setObjectName("Start")
        PrintHello.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PrintHello)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        PrintHello.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PrintHello)
        self.statusbar.setObjectName("statusbar")
        PrintHello.setStatusBar(self.statusbar)

        self.retranslateUi(PrintHello)
        QtCore.QMetaObject.connectSlotsByName(PrintHello)

    def retranslateUi(self, PrintHello):
        _translate = QtCore.QCoreApplication.translate
        PrintHello.setWindowTitle(_translate("PrintHello", "MainWindow"))
        self.LabHello.setText(_translate("PrintHello", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#5555ff;\">Hello World!</span></p></body></html>"))
        self.close.setText(_translate("PrintHello", "打开网址"))
        self.Start.setText(_translate("PrintHello", "<html><head/><body><p><a href=\"https://github.com/maicss/PyQt5-Chinese-tutorial\"><span style=\" font-size:14pt; font-weight:600; text-decoration: underline; color:#55aaff;\">A great start.</span></a></p></body></html>"))
